version: '3.4'

services:
  db:
    image: docker-proxy.dev.roscosmos.digital/postgres:14.2
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5050:80"

volumes:
  db_data:
    driver: local
