version: '3.4'

services:
  # db:
  #   image: docker-proxy.dev.roscosmos.digital/postgres:14.2
  #   hostname: "db"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: "123456"
  #     POSTGRES_DB: "postgres"
  #   ports:
  #     - 5432:5432 

  es01:
    image: docker-proxy.dev.roscosmos.digital/elastic/elasticsearch:7.10.1
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kib01:
    image: docker-proxy.dev.roscosmos.digital/elastic/kibana:7.10.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

volumes:
  data01:
    driver: local
  db_data:
    driver: local
