---
- hosts: all
  become: yes
  tasks:
    - name: Check that the docker-compose exists
      stat:
        path: /opt/marketplace/docker-compose.yml
      register: stat_result
      
    - name: Tear down existing services
      docker_compose:
        project_src: /opt/marketplace
        state: absent
      when: stat_result.stat.exists
    
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: ../deploy/docker-compose.yml
        dest: /opt/marketplace
        owner: devops
    
    - name: Copy env file
      ansible.builtin.copy:
        src: ../deploy/.env
        dest: /opt/marketplace
        owner: devops
    
    - name: Pull new images from Nexus
      docker_compose:
        project_src: /opt/marketplace
        pull: true
    
    - name: Start pulled services
      docker_compose:
        project_src: /opt/marketplace
        state: present
