// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/vue/views/AboutView.vue')['default']
    App: typeof import('./src/vue/App.vue')['default']
    AppLayout: typeof import('./src/vue/components/AppLayout.vue')['default']
    HelloWorld: typeof import('./src/vue/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/vue/views/HomeView.vue')['default']
    MainMenuContainer: typeof import('./src/vue/containers/MainMenuContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionsView: typeof import('./src/vue/views/SectionsView.vue')['default']
    ThemeSwitcher: typeof import('./src/vue/components/ThemeSwitcher.vue')['default']
  }
}
