// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/vue/views/AboutView.vue')['default']
    App: typeof import('./src/vue/App.vue')['default']
    AppLayout: typeof import('./src/vue/components/AppLayout.vue')['default']
    Card: typeof import('primevue/card')['default']
    CollectionState: typeof import('./src/vue/base/containers/state/CollectionState.vue')['default']
    CustomRender: typeof import('./src/vue/base/components/CustomRender.vue')['default']
    DataCard: typeof import('./src/vue/base/components/cards/DataCard.vue')['default']
    DataForm: typeof import('./src/vue/base/components/cards/DataForm.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Divider: typeof import('primevue/divider')['default']
    HelloWorld: typeof import('./src/vue/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/vue/views/HomeView.vue')['default']
    LoadingStatusHandler: typeof import('./src/vue/base/components/LoadingStatusHandler.vue')['default']
    MainMenuContainer: typeof import('./src/vue/containers/MainMenuContainer.vue')['default']
    PrimeDivider: typeof import('./src/vue/base/components/prime/PrimeDivider.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionsView: typeof import('./src/vue/views/SectionsView.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    ThemeSwitchContainer: typeof import('./src/vue/containers/ThemeSwitchContainer.vue')['default']
    TransitionFade: typeof import('./src/vue/components/transitions/TransitionFade.vue')['default']
  }
}
